### PR TITLE
Fix faucets (tmp)

### LINKED ISSUE #989: All faucets down
## Issue Type

```
[x ] bug report
```

## Current Behavior
Looks like at least the Goerli faucet is down. Can't find it on AWS anymore along. Alt-L2 faucets are running, but looks like the new Gateway doesn't update the metaAPI endpoint accordingly to use the Alt-L2 faucet (requests are not received on AWS as a consequence)

Thus, all faucets seem not to be accessible to the end user.

### PR DESCRIPTION
**Pull request by wsdt**
Resolves  https://github.com/bobanetwork/boba/issues/989

# Issue
Twitter API is paid now, all faucets were broken. 

# Changes
- Goerli faucet works again
- Updated goerli faucet contract configs & endpoint, funded turingCredit etc.
- Updated meta tx node version as not working with serverless anymore
- Ts-Node update as previous broken
- Changed serverless region to us-east-1 so that all meta tx are in the same region (might need DNS reconfig on update, already deployed)

Alt L2s not working yet, but don't think any code changes are required. 

Will create a separate Issue for proper Faucet redesign.

### CODE REVIEW

File: boba_community/hc-twitter/scripts/check_fill_turinghelper.ts [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+import L2GovernanceERC20Json
+  from "@eth-optimism/contracts/artifacts/contracts/standards/L2GovernanceERC20.sol/L2GovernanceERC20.json";
+import BobaTuringCreditJson
+  from "@eth-optimism/contracts/artifacts/contracts/L2/predeploys/BobaTuringCredit.sol/BobaTuringCredit.json";
+
+const cfg = hre.network.config
+
+async function main() {
+  const local_provider = new providers.JsonRpcProvider(cfg['url'])
+  const testPrivateKey = process.env.PRIVATE_KEY_FAUCET ?? '0x___________'
```
Comment (wsdt) [inline boba_community/hc-twitter/scripts/check_fill_turinghelper.ts:16]: Just a helper script

File: boba_community/hc-twitter/aws/loca-json-alternative.py [hunk 2]
```diff
@@ -0,0 +1,158 @@
...
+import json
+#import urllib3
+#import certifi
+import time
+import textwrap
+import hashlib
+import os
+from datetime import datetime
+
+authorized_contract = None  # for open access
```
Comment (wsdt) [inline boba_community/hc-twitter/aws/loca-json-alternative.py:12]: the file that is now deployed on AWS, needs redesign but fixes the faucet(s) now

**Comment by wsdt** [comment]
BNB faucet works again too - TuringCredit was unfunden. 
Avax & Opera work now too again.

**Review by InoMurko — APPROVED** [review]

**Review by souradeep-das — APPROVED** [review]
