### PR TITLE
Fix light mode buttons design

### LINKED ISSUE #679: In Light Mode Buttons Are hard to read

### PR DESCRIPTION
**Pull request by sk-enya**
:clipboard: Add associated issues, tickets, docs URL here.
closes: https://github.com/bobanetwork/boba/issues/679
## Overview

Design fixes for button in light mode.

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Wallet page Button style fixes in case of light mode.
- Tab Switcher button styles fixes in case of light mode.
- Alignment of cards in earn page.

## Testing
Please refer screen shot attached.
Screenshot 2023-03-28 at 1 00 39 PM
Screenshot 2023-03-28 at 12 30 27 PM

### CODE REVIEW

**Review by wsdt — APPROVED** [review]

File: packages/boba/gateway/src/components/listToken/listToken.js [hunk 1]
```diff
@@ -548,7 +548,7 @@ function ListToken({ token, chain, networkLayer, disabled, loading }) {
                   tooltip="Transfer funds from one L2 account to another L2 account."
                   fullWidth
                 >
-                  Transfer
+                  Transfer 1
```
Comment (boyuan-chen) [inline packages/boba/gateway/src/components/listToken/listToken.js]: Do we need to remove this 1?

**Review by alvaro-ricotta — APPROVED** [review]

File: packages/boba/gateway/src/components/listToken/listToken.js (hunk 1 above)
Comment (sk-enya) [reply packages/boba/gateway/src/components/listToken/listToken.js]: yup good catch! thank you.
