### PR TITLE
Fix [Gateway] : One gateway bridging

### LINKED ISSUE #584: Show loading / progress indicator on bridging tokens from L1 -> L2 & L2 -> L1

### LINKED ISSUE #587: Fee Switching: validate and fix. should only work in case of L2

### LINKED ISSUE #590: Validate and Fix Bridging From L2 -> L1
Validate the bridging for all the deployments.

1. classic L2 -> L1
2. fast L2 -> L1

Ethereum, BNB, AVAX, Fantom, MoonBeam

### LINKED ISSUE #612: One Gateway: Earn Page not working

### PR DESCRIPTION
**Pull request by sk-enya**
:clipboard: Add associated issues, tickets, docs URL here.

closes: https://github.com/bobanetwork/boba/issues/584

## Overview

Fix the design of bridging in the case of mobile and desktop

## Changes

- Close the bridge modal only when transactions are completed working `L1 -> L2`
- Fix fetch exit cost for **fast bridge to l1 / bridge to l1**
- Validated the changes for L2=>L1 Bridging for all the networks.
- Validated Fee switching on layer 2 from boba to native token and vice versa.
- Fix Farm Deposit along with style changes in modal
- Fix Farm withdrawal along with style changes in modal
- Disable unstake & stake more when selected to a different chain.

## Testing
Screenshot 2023-02-11 at 2 03 16 AM

### CODE REVIEW

File: packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js [hunk 1]
```diff
@@ -53,15 +53,15 @@ function FeeSwitcher() {
...
+  const l2BalanceNativeToken = l2Balances.filter((i) => i.symbol === networkService.L1NativeTokenSymbol)
+  const balanceETH = l2BalanceNativeToken[ 0 ]
   const l2BalanceBOBA = l2Balances.filter((i) => i.symbol === 'BOBA')
   const balanceBOBA = l2BalanceBOBA[ 0 ]
 
   const dispatchSwitchFee = useCallback(async (targetFee) => {
 
     let tooSmallL1NativeToken = false
-    let minL1NativeBalance = network === NETWORK.ETHEREUM ? 0.0002 : 0.5
+    let minL1NativeBalance = network === NETWORK.ETHEREUM ? 0.0002 : 0.002
```
Comment (wsdt) [inline packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js]: Could make sense to move this to .env? Especially since possibly different L2's might have a different min balance possibly?

**Review by wsdt — APPROVED** [review]

File: packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js (hunk 1 above)
Comment (boyuan-chen) [reply packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js]: Maybe check the minimum value from the smart contract? 
https://github.com/bobanetwork/boba/blob/54762652536b6c17bf79d7acd601efb36228b58e/packages/contracts/contracts/L2/predeploys/Boba_GasPriceOracle.sol#L29

This variable doesn't exist on Ethereum, so maybe use `try{}catch{}` and set a default value for Ethereum L2?

**Comment by boyuan-chen** [comment]
One bug might not be related to this PR:
After I close the MetaMask for switching the network, the `connect to XXX Network` button doesn't work.
image

**Comment by boyuan-chen** [comment]
I can't bridge Goerli ETH from L1 to L2. 
image
The problem can be reproduced when you switch network from Ethereum mainnet to Goerli testnet.
image

**Comment by boyuan-chen** [comment]
In wallet page, I click Boba wallet button to switch from Goerli L1 to L2 and confirmed it in MetaMask, the webpage doesn't automatically connect to network.

**Comment by boyuan-chen** [comment]
The earn page crashed when I clicked deposit BOBA.
image
image

File: packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js (hunk 1 above)
Comment (sk-enya) [reply packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js]: Yeah, @wsdt good point will move it constant file as of now.
@Boyuan-Chen, I was referring to the same smart contract but looking for **secondaryFeeTokenMinimum** as we are using it to check before switching to fee.

https://github.com/bobanetwork/boba/blob/54762652536b6c17bf79d7acd601efb36228b58e/packages/contracts/contracts/L2/predeploys/Boba_GasPriceOracle.sol#L73

In the case of Ethereum, it also seems to be `2e15` 
https://github.com/bobanetwork/boba/blob/develop/packages/contracts/contracts/L2/predeploys/Boba_GasPriceOracle.sol#L198

Comment (boyuan-chen) [reply packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js]: Yes! I referred to the wrong place. You are right!
https://github.com/bobanetwork/boba/blob/54762652536b6c17bf79d7acd601efb36228b58e/packages/contracts/contracts/L2/predeploys/Boba_GasPriceOracle.sol#L73

**Comment by sk-enya** [comment]
@Boyuan-Chen  thank you for sharing your findings.

I fixed the below two issues. 
1/ crash on the earn page
2/ Network switching on closing meta mask

I spent much time fixing other issues but was unable to crack it down as it seems to need reorder initializeBase & initializeAccount prepare the separate issue list for this will consider this in another branch.

File: packages/boba/gateway/src/util/constant.js [hunk 2]
```diff
@@ -100,3 +100,5 @@ export const DEFAULT_NETWORK = {
 
 
 export const MM_EXTENTION_URL = 'https://chrome.google.com/webstore/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn?hl=en'
+
+export const MIN_NATIVE_L1_BALANCE = 0.002
```
Comment (InoMurko) [inline packages/boba/gateway/src/util/constant.js:102]: @Boyuan-Chen is this ok?

Comment (sk-enya) [reply packages/boba/gateway/src/util/constant.js:102]: Just note:
 This var is getting used in the case of Ethereum! just moved to constant file from `layerswitcher.js`

**Review by boyuan-chen — APPROVED** [review]

File: packages/boba/gateway/src/util/constant.js (hunk 2 above)
Comment (boyuan-chen) [reply packages/boba/gateway/src/util/constant.js:102]: 0.002 is the default value, so it's ok.
